<Project>

  <PropertyGroup>

    <Version>1.5.5</Version>

    <AssemblyVersion>1.5.5.0</AssemblyVersion>

    <FileVersion>1.5.5.0</FileVersion>

    <InformationalVersion>1.5.5</InformationalVersion>

    <CaveInstallerProductVersion>1.5.5.0</CaveInstallerProductVersion>

  </PropertyGroup>

</Project>


