<Project>

  <PropertyGroup>

    <Version>1.5.15</Version>

    <AssemblyVersion>1.5.15.0</AssemblyVersion>

    <FileVersion>1.5.15.0</FileVersion>

    <InformationalVersion>1.5.15</InformationalVersion>

    <CaveInstallerProductVersion>1.5.15.0</CaveInstallerProductVersion>

  </PropertyGroup>

</Project>


